# Generated by Django 5.2.17 on 2026-09-28 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0012_subscriptionpaymentrequest_montant_catalogue_and_more'),
        ('tenants', '0004_retrait_offres_solo_salon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeParrainage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='code')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_parrainage', to='tenants.tenant', verbose_name='salon')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_parrainage', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'code de parrainage',
                'verbose_name_plural': 'codes de parrainage',
            },
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_parrain', models.CharField(choices=[('salon', 'Salon'), ('utilisateur', 'Utilisateur')], max_length=12, verbose_name='type de parrain')),
                ('statut', models.CharField(choices=[('en_verification', 'En vérification'), ('admissible', 'Admissible'), ('refuse', 'Refusé'), ('invalide', 'Invalidé')], default='en_verification', max_length=20, verbose_name='statut')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('revue_requise', models.BooleanField(default=False, verbose_name='revue requise')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='filleul publié le')),
                ('admissible_le', models.DateTimeField(blank=True, null=True, verbose_name='admissible le')),
                ('empreinte_ip', models.CharField(blank=True, max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='détecté le')),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parrainages', to='parrainage.codeparrainage', verbose_name='code utilisé')),
                ('filleul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_recu', to='tenants.tenant', verbose_name='salon filleul')),
                ('parrain_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parrainages_donnes', to='tenants.tenant', verbose_name='salon parrain')),
                ('parrain_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parrainages_donnes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur parrain')),
            ],
            options={
                'verbose_name': 'parrainage',
                'verbose_name_plural': 'parrainages',
                'ordering': ('-cree_le',),
                'permissions': [('corriger_parrainage', 'Peut corriger les parrainages et leurs remises')],
            },
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filleul_nom', models.CharField(max_length=120, verbose_name='salon filleul')),
                ('declencheur', models.CharField(choices=[('inscription', 'Inscription admissible du filleul'), ('paiement', 'Paiement approuvé du filleul')], max_length=12, verbose_name='déclencheur')),
                ('reference', models.CharField(max_length=80, unique=True, verbose_name="référence de l'événement")),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pourcentage')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reservee', 'Réservée'), ('utilisee', 'Utilisée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='disponible', max_length=12, verbose_name='statut')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('montant_deduit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant déduit')),
                ('devise', models.CharField(blank=True, max_length=3, verbose_name='devise')),
                ('utilisee_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisée le')),
                ('annulee_le', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('beneficiaire_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises_parrainage', to='tenants.tenant', verbose_name='salon bénéficiaire')),
                ('beneficiaire_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises_parrainage', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur bénéficiaire')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_parrainage', to='billing.subscriptionpaymentrequest', verbose_name='paiement concerné')),
                ('parrainage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises', to='parrainage.parrainage')),
            ],
            options={
                'verbose_name': 'remise de parrainage',
                'verbose_name_plural': 'remises de parrainage',
                'ordering': ('expire_le',),
            },
        ),
        migrations.AddConstraint(
            model_name='codeparrainage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tenant__isnull', False), ('user__isnull', True)), models.Q(('tenant__isnull', True), ('user__isnull', False)), _connector='OR'), name='code_parrainage_un_seul_titulaire'),
        ),
        migrations.AddIndex(
            model_name='parrainage',
            index=models.Index(fields=['statut'], name='parrainage__statut_088f38_idx'),
        ),
        migrations.AddIndex(
            model_name='remise',
            index=models.Index(fields=['statut', 'expire_le'], name='parrainage__statut_040fce_idx'),
        ),
        migrations.AddConstraint(
            model_name='remise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('beneficiaire_tenant__isnull', False), ('beneficiaire_user__isnull', True)), models.Q(('beneficiaire_tenant__isnull', True), ('beneficiaire_user__isnull', False)), _connector='OR'), name='remise_un_seul_beneficiaire'),
        ),
        migrations.AddConstraint(
            model_name='remise',
            constraint=models.CheckConstraint(condition=models.Q(('pourcentage__gt', 0), ('pourcentage__lte', 100)), name='remise_pourcentage_valide'),
        ),
    ]
