# Generated by Django 5.2.17 on 2026-10-08 17:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_subscriptionpaymentrequest_etat_encaissement_and_more'),
        ('parrainage', '0001_initial'),
        ('scheduling', '0017_booking_prix_initial_booking_promotion_montant_and_more'),
        ('tenants', '0005_alter_tenant_country_alter_tenant_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolitiquePlateforme',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('cooling_jours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooling_mode', models.CharField(choices=[('demi_periode', 'Moitié de la période payée'), ('jours', 'Nombre de jours')], default='demi_periode', max_length=20)),
                ('validite_jours', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('validite_depuis_disponibilite', models.BooleanField(default=False)),
                ('recompenses_max_par_parrain', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('remises_max_par_echeance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('reservation_heures', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('apres_remboursement', models.CharField(blank=True, choices=[('revue', 'Suspendre et demander une décision'), ('maintenir', 'Maintenir les récompenses disponibles/utilisées')], max_length=20)),
            ],
            options={
                'verbose_name': 'politique de parrainage plateforme (Cas B)',
                'verbose_name_plural': 'politique de parrainage plateforme (Cas B)',
            },
        ),
        migrations.AddField(
            model_name='parrainage',
            name='essai_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parrainage',
            name='essai_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remise',
            name='conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='remise',
            name='disponible_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remise',
            name='paiement_confirme_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remise',
            name='paiement_declencheur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompenses_declenchees', to='billing.subscriptionpaymentrequest'),
        ),
        migrations.AlterField(
            model_name='remise',
            name='expire_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire le'),
        ),
        migrations.AlterField(
            model_name='remise',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente du délai de sécurité'), ('suspendue', 'Suspendue pour vérification'), ('disponible', 'Disponible'), ('reservee', 'Réservée'), ('utilisee', 'Utilisée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='disponible', max_length=12, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='CodeClientSalon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='code_client_salon_unique')],
            },
        ),
        migrations.CreateModel(
            name='EvenementParrainage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cas', models.CharField(choices=[('A', 'Client vers client'), ('B', 'Vers salon')], max_length=1)),
                ('ressource', models.UUIDField()),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['cas', 'ressource', 'cree_le'], name='parrainage__cas_d5014f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolitiqueSalon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('taux', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('validite_jours', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('plafond_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(blank=True, max_length=3)),
                ('nature_plafond', models.CharField(blank=True, choices=[('montant_par_reservation', 'Montant maximal de réduction par réservation')], max_length=30)),
                ('reservations_annulees_excluent', models.BooleanField(blank=True, null=True)),
                ('attribution', models.CharField(blank=True, choices=[('premier_code', 'Premier code valide')], max_length=20)),
                ('formule', models.CharField(blank=True, choices=[('apres_promotions_prestation', 'Après promotions, prestation et options')], max_length=40)),
                ('recompenses_par_reservation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annulation_declencheur', models.CharField(blank=True, choices=[('revue', 'Suspendre pour décision'), ('maintenir', 'Maintenir')], max_length=20)),
                ('annulation_utilisation', models.CharField(blank=True, choices=[('revue', 'Suspendre pour décision'), ('restituer', 'Restituer si encore valide'), ('maintenir', 'Maintenir la consommation')], max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'politique de parrainage salon (Cas A)',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='politique_parrainage_salon_unique')],
            },
        ),
        migrations.CreateModel(
            name='RecompenseClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identite_filleul', models.CharField(max_length=64)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plafond_montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(max_length=3)),
                ('conditions', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('en_attente', 'Première réservation à confirmer'), ('disponible', 'Disponible'), ('reservee', 'Réservée'), ('utilisee', 'Utilisée'), ('annulee', 'Annulée'), ('expiree', 'Expirée'), ('suspendue', 'À vérifier')], default='en_attente', max_length=12)),
                ('disponible_le', models.DateTimeField(blank=True, null=True)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('montant_deduit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('declencheur', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parrainage_client', to='scheduling.booking')),
                ('filleul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parrainages_clients_recus', to=settings.AUTH_USER_MODEL)),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recompenses_clients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
                ('utilisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reduction_parrainage_client', to='scheduling.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'parrain', 'statut'], name='parrainage__tenant__4ce817_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'identite_filleul'), name='premier_parrainage_client_salon')],
            },
        ),
    ]
