# Generated by Django 5.2.17 on 2026-10-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0004_alter_recompenseclient_parrain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeclientsalon',
            options={'verbose_name': 'code de parrainage client', 'verbose_name_plural': 'codes de parrainage clients (Cas A)'},
        ),
        migrations.AlterModelOptions(
            name='evenementparrainage',
            options={'ordering': ['-cree_le'], 'verbose_name': 'événement de parrainage', 'verbose_name_plural': 'journal du parrainage (Cas A/B)'},
        ),
        migrations.AlterModelOptions(
            name='politiquesalon',
            options={'verbose_name': 'politique de parrainage salon (Cas A)', 'verbose_name_plural': 'politiques de parrainage des salons (Cas A)'},
        ),
        migrations.AlterModelOptions(
            name='recompenseclient',
            options={'verbose_name': 'récompense client', 'verbose_name_plural': 'récompenses clients (Cas A)'},
        ),
    ]
