# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('manager', 'Gérant'), ('receptionist', 'Réceptionniste'), ('staff', 'Prestataire')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invité'), ('active', 'Actif'), ('disabled', 'Désactivé')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nom affiché'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='téléphone'),
        ),
    ]
