# Generated by Django 5.2.17 on 2026-09-08 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_membership_role_alter_membership_status_and_more'),
        ('tenants', '0002_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('manager', 'Gérant'), ('receptionist', 'Réceptionniste'), ('staff', 'Prestataire')], default='staff', max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'invitation',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'email'], name='accounts_in_tenant__991c2e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('tenant', 'email'), name='one_pending_invitation_per_email')],
            },
        ),
    ]
