# Generated by Django 5.2.17 on 2026-09-08 03:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='presentation')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('service_mode', models.CharField(choices=[('salon', 'Au salon'), ('home', 'A domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telephone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=32, verbose_name='numero WhatsApp')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
                ('cancellation_policy', models.TextField(blank=True, verbose_name="politique d'annulation")),
                ('cancellation_deadline_hours', models.PositiveSmallIntegerField(default=24)),
                ('slot_granularity_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(240)])),
                ('min_lead_time_minutes', models.PositiveSmallIntegerField(default=120)),
                ('max_advance_days', models.PositiveSmallIntegerField(default=90)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'profil de salon',
                'verbose_name_plural': 'profils de salon',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='one_profile_per_tenant')],
            },
        ),
    ]
