# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='présentation'),
        ),
        migrations.AlterField(
            model_name='salonprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='salonprofile',
            name='service_mode',
            field=models.CharField(choices=[('salon', 'Au salon'), ('home', 'À domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10),
        ),
        migrations.AlterField(
            model_name='salonprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='numéro WhatsApp'),
        ),
    ]
