# Generated by Django 5.2.17 on 2026-09-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediaasset_tenant'),
        ('salons', '0004_alter_salonprofile_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='about_content',
            field=models.TextField(blank=True, verbose_name='texte de la page À propos'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='photo de la page À propos'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='about_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='titre de la page À propos'),
        ),
        migrations.AlterField(
            model_name='salonprofile',
            name='cancellation_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, verbose_name="annulation gratuite jusqu'à (heures avant)"),
        ),
    ]
