# Generated by Django 5.2.17 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salonprofile_about_content_salonprofile_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='late_policy',
            field=models.TextField(blank=True, help_text="Ce qu'il advient d'un rendez-vous au-delà de la tolérance. Affiché sur votre mini-site et rappelé dans l'e-mail de confirmation.", verbose_name='politique de retard'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='late_tolerance_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text="Au-delà de ce délai, l'agenda signale le rendez-vous comme en retard.", verbose_name='tolérance de retard (minutes)'),
        ),
    ]
