# Generated by Django 5.2.17 on 2026-09-10 11:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_politique_de_retard'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='service_area',
            field=models.CharField(blank=True, help_text='Les quartiers où vous vous déplacez, séparés par des virgules.', max_length=255, verbose_name='zone desservie'),
        ),
        migrations.CreateModel(
            name='TravelZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='quartier ou zone')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 pour une zone desservie gratuitement.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='frais de déplacement')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='proposée à la réservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'zone de déplacement',
                'verbose_name_plural': 'zones de déplacement',
                'ordering': ('position', 'name'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_travel_zone_per_tenant')],
            },
        ),
    ]
