# Generated by Django 5.2.17 on 2026-09-13 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_rls_travelzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonprofile',
            name='max_advance_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='salonprofile',
            name='min_lead_time_minutes',
            field=models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(10080)]),
        ),
    ]
