# Generated by Django 5.2.17 on 2026-09-13 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0009_horizon_de_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='deposit_covers_items',
            field=models.BooleanField(default=True, help_text="Les articles de votre boutique sont payés d'avance : vous les avez déjà achetés.", verbose_name='faire régler les fournitures en entier'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='deposit_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text="Part de la prestation et des options demandée à la réservation. 0 pour s'en tenir au montant fixe de chaque prestation.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='acompte demandé (%)'),
        ),
    ]
