# Generated by Django 5.2.17 on 2026-09-15 17:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_calcul_acompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='deposit_minimum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Plancher, quel que soit le pourcentage. Utile sur les petites prestations, où un pourcentage ne couvre pas le créneau perdu.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='acompte minimum'),
        ),
        migrations.AlterField(
            model_name='salonprofile',
            name='deposit_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='Part de la prestation et des options demandée à la réservation.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='acompte demandé (%)'),
        ),
    ]
