# Generated by Django 5.2.17 on 2026-09-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_genre_qr_wechat'),
        ('salons', '0011_acompte_regle_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonprofile',
            name='wechat_id',
            field=models.CharField(blank=True, help_text="Le numero WeChat du salon, tel qu'on le tape pour le chercher.", max_length=64, verbose_name='identifiant WeChat'),
        ),
        migrations.AddField(
            model_name='salonprofile',
            name='wechat_qr',
            field=models.ForeignKey(blank=True, help_text='Le code a scanner pour ajouter le salon en contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='QR code WeChat'),
        ),
    ]
