# Generated by Django 5.2.17 on 2026-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salons", "0013_retrait_du_lien_wechat"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail de contact"),
        ),
    ]
