# Generated by Django 5.2.17 on 2026-09-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salons", "0015_email_de_contact_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonprofile",
            name="site_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
