# Generated by Django 5.2.17 on 2026-09-13 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0005_mediaasset_featured_alter_mediaasset_position'),
        ('scheduling', '0012_articles_achetes'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, choices=[('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('bank', 'Virement bancaire')], max_length=20, verbose_name='moyen utilisé')),
                ('reference', models.CharField(blank=True, help_text="Numéro de transaction, si la cliente l'a noté.", max_length=120, verbose_name='référence du versement')),
                ('note', models.TextField(blank=True, verbose_name='message de la cliente')),
                ('status', models.CharField(choices=[('submitted', 'Envoyée, en attente de vérification'), ('accepted', 'Versement retrouvé'), ('rejected', 'Versement introuvable')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='motif du refus')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_proof', to='scheduling.booking', verbose_name='rendez-vous')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name="capture d'écran")),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vérifié par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'preuve de versement',
                'verbose_name_plural': 'preuves de versement',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('bank', 'Virement bancaire')], max_length=20, verbose_name='moyen de paiement')),
                ('account_name', models.CharField(blank=True, help_text="Ce que la cliente verra s'afficher en scannant.", max_length=150, verbose_name='nom du compte')),
                ('instructions', models.CharField(blank=True, help_text='« Mettez votre nom en commentaire », par exemple.', max_length=255, verbose_name='précision')),
                ('active', models.BooleanField(default=True, verbose_name='proposé à la réservation')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('qr_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='QR code')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': "moyen d'encaissement",
                'verbose_name_plural': "moyens d'encaissement",
                'ordering': ('position', 'kind'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind'), name='unique_payment_channel_per_tenant')],
            },
        ),
    ]
