# Generated by Django 5.2.17 on 2026-09-10 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_invitation_tenant'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp')),
                ('wechat', models.CharField(blank=True, max_length=64, verbose_name='WeChat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant', verbose_name='salon favori')),
            ],
            options={
                'verbose_name': 'compte cliente',
                'verbose_name_plural': 'comptes clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientSalonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rattachement à un salon',
                'verbose_name_plural': 'rattachements aux salons',
                'indexes': [models.Index(fields=['user'], name='clients_cli_user_id_a68bd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='one_link_per_client_and_salon')],
            },
        ),
    ]
