# Generated by Django 5.2.17 on 2026-09-13 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_comptes_clientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visite masquée',
                'verbose_name_plural': 'visites masquées',
                'indexes': [models.Index(fields=['user'], name='clients_hid_user_id_59a1bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'booking_id'), name='one_hidden_row_per_booking')],
            },
        ),
    ]
