# Generated by Django 5.2.17 on 2026-09-11 01:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_alter_invoice_tenant_alter_subscription_tenant'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10, verbose_name='sens')),
                ('category', models.CharField(max_length=30, verbose_name='poste')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('subscription', "Facture d'abonnement réglée")], default='manual', max_length=20, verbose_name='origine')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('occurred_on', models.DateField(verbose_name='date')),
                ('note', models.TextField(blank=True, verbose_name='détail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_entries', to='billing.invoice', verbose_name="facture d'origine")),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant', verbose_name='salon concerné')),
            ],
            options={
                'verbose_name': 'mouvement plateforme',
                'verbose_name_plural': 'comptes de la plateforme',
                'ordering': ('-occurred_on', '-created_at'),
                'indexes': [models.Index(fields=['kind', 'occurred_on'], name='platformled_kind_d9437a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='platform_entry_amount_is_positive'), models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice',), name='one_platform_entry_per_invoice')],
            },
        ),
    ]
