# Generated by Django 5.2.17 on 2026-09-08 03:37

import apps.media.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to=apps.media.models.upload_to)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('gallery', 'Galerie'), ('logo', 'Logo'), ('banner', 'Banniere'), ('service', 'Prestation'), ('staff', 'Prestataire')], default='gallery', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Publique'), ('private', 'Privee')], default='public', max_length=10)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'medias',
                'ordering': ('position', '-created_at'),
                'indexes': [models.Index(fields=['tenant', 'kind', 'position'], name='media_media_tenant__72a03b_idx')],
            },
        ),
    ]
