# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ('position', '-created_at'), 'verbose_name': 'média', 'verbose_name_plural': 'médias'},
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('gallery', 'Galerie'), ('logo', 'Logo'), ('banner', 'Bannière'), ('service', 'Prestation'), ('staff', 'Prestataire')], default='gallery', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publique'), ('private', 'Privée')], default='public', max_length=10),
        ),
    ]
