# Generated by Django 5.2.17 on 2026-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediaasset_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='featured',
            field=models.BooleanField(default=False, verbose_name="en vedette sur l'accueil"),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage"),
        ),
    ]
