# Generated by Django 5.2.17 on 2026-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_medias_prives_hors_racine_publique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('gallery', 'Galerie'), ('logo', 'Logo'), ('banner', 'Bannière'), ('service', 'Prestation'), ('staff', 'Prestataire'), ('payment', 'QR de paiement'), ('wechat', 'QR de contact WeChat'), ('about', 'Page À propos'), ('product', 'Article de boutique'), ('proof', 'Preuve de versement')], default='gallery', max_length=20),
        ),
    ]
