# Generated by Django 5.2.17 on 2026-10-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_aligner_le_lieu_sur_le_salon'),
        ('media', '0010_reparer_medias_prives'),
        ('staff', '0005_retrait_de_la_liste'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='catalog.service', verbose_name='prestation montrée'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='staff.staffmember', verbose_name='réalisée par'),
        ),
    ]
