# Generated by Django 5.2.17 on 2026-09-08 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('phone', models.CharField(max_length=32, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_preference', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Telephone'), ('email', 'E-mail')], default='whatsapp', max_length=20)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('marketing_consent_at', models.DateTimeField(blank=True, null=True)),
                ('private_notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['tenant', 'phone'], name='customers_c_tenant__6d2a04_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_customer_phone_per_tenant')],
            },
        ),
    ]
