# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_preference',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Téléphone'), ('email', 'E-mail')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='téléphone'),
        ),
    ]
