# Generated by Django 5.2.17 on 2026-09-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_contact_preference_and_more'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon'),
        ),
    ]
