# Generated by Django 5.2.17 on 2026-09-11 00:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0011_rls_liste_attente'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10, verbose_name='sens')),
                ('category', models.CharField(max_length=30, verbose_name='poste')),
                ('label', models.CharField(help_text="Ce que c'était, en clair. « Mèches kanekalon », « loyer mars ».", max_length=200, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('occurred_on', models.DateField(verbose_name='date')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement'), ('card', 'Carte'), ('wechat', 'WeChat Pay'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='moyen')),
                ('counterparty', models.CharField(blank=True, max_length=150, verbose_name='origine ou bénéficiaire')),
                ('note', models.TextField(blank=True, verbose_name='détail')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='scheduling.booking', verbose_name="rendez-vous d'origine")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'mouvement',
                'verbose_name_plural': 'recettes et dépenses',
                'ordering': ('-occurred_on', '-created_at'),
                'indexes': [models.Index(fields=['tenant', 'occurred_on'], name='finance_tra_tenant__ae651a_idx'), models.Index(fields=['tenant', 'kind', 'occurred_on'], name='finance_tra_tenant__91d232_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_is_positive')],
            },
        ),
    ]
