# Generated by Django 5.2.17 on 2026-09-11 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_tenant_alter_subscription_tenant'),
        ('finance', '0002_rls'),
        ('scheduling', '0011_rls_liste_attente'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.invoice', verbose_name="facture d'origine"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('booking_deposit', 'Acompte encaissé'), ('booking_balance', 'Solde de la prestation'), ('subscription', 'Abonnement à la plateforme')], default='manual', max_length=20, verbose_name='origine'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='scheduling.booking', verbose_name="rendez-vous d'origine"),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'source'), name='one_transaction_per_booking_and_source'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('invoice',), name='one_transaction_per_invoice'),
        ),
    ]
