# Generated by Django 5.2.17 on 2026-09-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_origine_des_lignes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('booking_deposit', 'Acompte encaissé'), ('booking_balance', 'Solde de la prestation'), ('booking_items', 'Vente au comptoir'), ('subscription', 'Abonnement à la plateforme')], default='manual', max_length=20, verbose_name='origine'),
        ),
    ]
