# Generated by Django 5.2.17 on 2026-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_vente_au_comptoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('booking_deposit', 'Acompte encaissé'), ('booking_balance', 'Solde de la prestation'), ('booking_items', 'Vente au comptoir'), ('booking_travel', 'Forfait de déplacement'), ('subscription', 'Abonnement à la plateforme')], default='manual', max_length=20, verbose_name='origine'),
        ),
    ]
