# Generated by Django 5.2.17 on 2026-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_devise_de_l_ecriture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement'), ('card', 'Carte'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='moyen'),
        ),
    ]
