# Generated by Django 5.2.17 on 2026-09-08 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('booking.created', 'Reservation creee'), ('booking.cancelled', 'Reservation annulee'), ('booking.rescheduled', 'Reservation deplacee'), ('booking.status_changed', 'Statut modifie'), ('customer.notes_viewed', 'Notes clientes consultees'), ('tenant.created', 'Salon cree'), ('membership.changed', 'Membership modifie'), ('tenant.access_denied', 'Acces croise refuse')], max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': "evenement d'audit",
                'verbose_name_plural': "evenements d'audit",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='audit_audit_tenant__1d7666_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
