# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': "événement d'audit", 'verbose_name_plural': "événements d'audit"},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('booking.created', 'Réservation créée'), ('booking.cancelled', 'Réservation annulée'), ('booking.rescheduled', 'Réservation déplacée'), ('booking.status_changed', 'Statut modifié'), ('customer.notes_viewed', 'Notes clientes consultées'), ('tenant.created', 'Salon créé'), ('membership.changed', 'Membership modifié'), ('tenant.access_denied', 'Accès croisé refusé')], max_length=64),
        ),
    ]
