# Generated by Django 5.2.17 on 2026-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('booking.created', 'Réservation créée'), ('booking.cancelled', 'Réservation annulée'), ('booking.rescheduled', 'Réservation déplacée'), ('booking.status_changed', 'Statut modifié'), ('customer.notes_viewed', 'Notes clientes consultées'), ('tenant.created', 'Salon créé'), ('tenant.status_changed', 'Statut du salon modifié'), ('membership.changed', 'Membership modifié'), ('tenant.access_denied', 'Accès croisé refusé'), ('platform.deleted', "Supprimé depuis l'administration")], max_length=64),
        ),
    ]
