# Generated by Django 5.2.17 on 2026-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('booking.created', 'Réservation créée'), ('booking.cancelled', 'Réservation annulée'), ('booking.rescheduled', 'Réservation déplacée'), ('booking.status_changed', 'Statut modifié'), ('customer.notes_viewed', 'Notes clientes consultées'), ('tenant.created', 'Salon créé'), ('tenant.status_changed', 'Statut du salon modifié'), ('membership.changed', 'Membership modifié'), ('tenant.access_denied', 'Accès croisé refusé'), ('platform.deleted', "Supprimé depuis l'administration"), ('subscription.payment_submitted', "Paiement d'abonnement déclaré"), ('subscription.payment_approved', "Paiement d'abonnement approuvé"), ('subscription.payment_rejected', "Paiement d'abonnement refusé"), ('subscription.manual_change', 'Abonnement modifié à la main'), ('billing.settings_changed', 'Tarifs ou moyens de règlement modifiés')], max_length=64),
        ),
    ]
