# Generated by Django 5.2.17 on 2026-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_actions_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('booking.created', 'Réservation créée'), ('booking.cancelled', 'Réservation annulée'), ('booking.rescheduled', 'Réservation déplacée'), ('booking.status_changed', 'Statut modifié'), ('customer.notes_viewed', 'Notes clientes consultées'), ('tenant.created', 'Salon créé'), ('tenant.status_changed', 'Statut du salon modifié'), ('membership.changed', 'Membership modifié'), ('tenant.access_denied', 'Accès croisé refusé'), ('platform.deleted', "Supprimé depuis l'administration"), ('subscription.payment_submitted', "Paiement d'abonnement déclaré"), ('subscription.payment_approved', "Paiement d'abonnement approuvé"), ('subscription.payment_rejected', "Paiement d'abonnement refusé"), ('subscription.manual_change', 'Abonnement modifié à la main'), ('billing.settings_changed', 'Tarifs ou moyens de règlement modifiés'), ('domain.claimed', 'Domaine personnalisé demandé'), ('domain.connected', 'Domaine personnalisé relié'), ('domain.removed', 'Domaine personnalisé retiré'), ('site.customized', 'Personnalisation du site modifiée'), ('assistant.settings_changed', 'Réglages des assistants IA modifiés'), ('tenant.deleted', 'Salon supprimé définitivement'), ('user.deleted', 'Compte supprimé définitivement')], max_length=64),
        ),
    ]
