# Generated by Django 5.2.17 on 2026-10-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('booking.created', 'Réservation créée'), ('booking.cancelled', 'Réservation annulée'), ('booking.rescheduled', 'Réservation déplacée'), ('booking.status_changed', 'Statut modifié'), ('customer.notes_viewed', 'Notes clientes consultées'), ('tenant.created', 'Salon créé'), ('tenant.status_changed', 'Statut du salon modifié'), ('membership.changed', 'Membership modifié'), ('tenant.access_denied', 'Accès croisé refusé'), ('platform.deleted', "Supprimé depuis l'administration"), ('subscription.payment_submitted', "Paiement d'abonnement déclaré"), ('subscription.payment_approved', "Paiement d'abonnement approuvé"), ('subscription.payment_rejected', "Paiement d'abonnement refusé"), ('subscription.manual_change', 'Abonnement modifié à la main'), ('billing.settings_changed', 'Tarifs ou moyens de règlement modifiés'), ('domain.claimed', 'Domaine personnalisé demandé'), ('domain.connected', 'Domaine personnalisé relié'), ('domain.removed', 'Domaine personnalisé retiré'), ('site.customized', 'Personnalisation du site modifiée'), ('assistant.settings_changed', 'Réglages des assistants IA modifiés'), ('tenant.deleted', 'Salon supprimé définitivement'), ('user.deleted', 'Compte supprimé définitivement'), ('referral.detected', 'Parrainage détecté'), ('referral.eligible', 'Parrainage admissible'), ('referral.review_required', 'Parrainage à revoir'), ('referral.reward_created', 'Remise de parrainage créée'), ('referral.admin', "Parrainage corrigé par l'administration"), ('auth.login_succeeded', 'Connexion réussie'), ('auth.login_failed', 'Connexion échouée'), ('auth.account_locked', "Connexions suspendues (trop d'échecs)"), ('auth.mfa_failed', 'Code de double authentification refusé'), ('auth.mfa_enabled', 'Double authentification activée'), ('auth.mfa_disabled', 'Double authentification désactivée'), ('auth.recovery_codes_regenerated', 'Codes de secours régénérés'), ('auth.password_reset', 'Mot de passe réinitialisé'), ('auth.password_changed', 'Mot de passe changé'), ('auth.email_changed', 'Adresse e-mail changée'), ('auth.email_verified', 'Adresse e-mail vérifiée'), ('auth.password_breached', 'Mot de passe refusé (présent dans des fuites)')], max_length=64),
        ),
    ]
