# Generated by Django 5.2.17 on 2026-09-26 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantReglages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clientes_actif', models.BooleanField(default=True, verbose_name='assistant du mini-site actif')),
                ('whatsapp_actif', models.BooleanField(default=False, verbose_name='réponses automatiques WhatsApp')),
                ('whatsapp_instance', models.CharField(blank=True, db_index=True, max_length=64)),
                ('whatsapp_empreinte', models.CharField(blank=True, max_length=64, verbose_name='empreinte du jeton du webhook')),
                ('whatsapp_statut', models.CharField(choices=[('aucun', 'Non connecté'), ('en_attente', 'QR code à scanner'), ('connecte', 'Connecté'), ('deconnecte', 'Déconnecté')], default='aucun', max_length=12)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=32)),
                ('whatsapp_derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'réglages des assistants',
                'verbose_name_plural': 'réglages des assistants',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='un_reglage_assistant_par_salon')],
            },
        ),
    ]
