# Generated by Django 5.2.17 on 2026-10-03 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_rls'),
        ('tenants', '0004_retrait_offres_solo_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantreglages',
            name='n8n_cle',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='assistantreglages',
            name='n8n_derniere_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantreglages',
            name='n8n_empreinte',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assistantreglages',
            name='n8n_numero',
            field=models.CharField(blank=True, max_length=32, verbose_name="numéro WhatsApp de l'assistant"),
        ),
        migrations.CreateModel(
            name='ConversationAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp (passerelle de la plateforme)'), ('n8n', 'n8n')], max_length=12)),
                ('contact', models.CharField(max_length=64, verbose_name='contact')),
                ('nom', models.CharField(blank=True, max_length=120, verbose_name='nom affiché')),
                ('dernier_message_le', models.DateTimeField(db_index=True)),
                ('dernier_apercu', models.CharField(blank=True, max_length=200)),
                ('nombre_messages', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': "conversation de l'assistant",
                'verbose_name_plural': "conversations de l'assistant",
                'ordering': ('-dernier_message_le',),
            },
        ),
        migrations.CreateModel(
            name='MessageAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('entrant', 'Reçu'), ('sortant', 'Envoyé')], max_length=8)),
                ('texte', models.TextField()),
                ('envoye_le', models.DateTimeField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistants.conversationassistant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': "message de l'assistant",
                'verbose_name_plural': "messages de l'assistant",
                'ordering': ('envoye_le',),
            },
        ),
        migrations.AddConstraint(
            model_name='conversationassistant',
            constraint=models.UniqueConstraint(fields=('tenant', 'canal', 'contact'), name='une_conversation_par_contact'),
        ),
        migrations.AddConstraint(
            model_name='messageassistant',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('tenant', 'reference'), name='un_message_par_reference'),
        ),
    ]
