# Generated by Django 5.2.17 on 2026-09-08 03:37

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Uniquement des minuscules, chiffres et tirets.', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')], verbose_name='identifiant')),
                ('status', models.CharField(choices=[('pending', 'En preparation'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('plan', models.CharField(choices=[('trial', 'Essai'), ('solo', 'Solo'), ('salon', 'Salon'), ('pro', 'Pro')], default='trial', max_length=20)),
                ('country', models.CharField(choices=[('CG', 'Congo-Brazzaville'), ('CD', 'Republique democratique du Congo'), ('CN', 'Chine')], default='CG', max_length=2)),
                ('timezone', models.CharField(default='Africa/Brazzaville', max_length=64)),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('CDF', 'Franc congolais'), ('CNY', 'Yuan'), ('USD', 'Dollar americain'), ('EUR', 'Euro')], default='XAF', max_length=3)),
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salons',
                'ordering': ('name',),
            },
        ),
    ]
