# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('CG', 'Congo-Brazzaville'), ('CD', 'République démocratique du Congo'), ('CN', 'Chine')], default='CG', max_length=2),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Franc CFA'), ('CDF', 'Franc congolais'), ('CNY', 'Yuan'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], default='XAF', max_length=3),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending', 'En préparation'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='pending', max_length=20),
        ),
    ]
