# Generated by Django 5.2.17 on 2026-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('CG', 'Congo-Brazzaville'), ('CD', 'République démocratique du Congo'), ('CN', 'Chine')], default='CG', max_length=2, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Franc CFA'), ('CDF', 'Franc congolais'), ('CNY', 'Yuan'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], default='XAF', max_length=3, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Essai'), ('solo', 'Solo'), ('salon', 'Salon'), ('pro', 'Pro')], default='trial', max_length=20, verbose_name='offre'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('pending', 'En préparation'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Africa/Brazzaville', max_length=64, verbose_name='fuseau horaire'),
        ),
    ]
