# Generated by Django 5.2.17 on 2026-09-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='plan',
        ),
    ]
