# Generated by Django 5.2.17 on 2026-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_retrait_offres_solo_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('CG', 'Congo-Brazzaville'), ('CD', 'République démocratique du Congo'), ('CN', 'Chine'), ('BJ', 'Bénin'), ('CI', 'Côte d’Ivoire'), ('TG', 'Togo'), ('SN', 'Sénégal'), ('NE', 'Niger')], default='CG', max_length=2, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Franc CFA'), ('XOF', 'Franc CFA BCEAO'), ('CDF', 'Franc congolais'), ('CNY', 'Yuan'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], default='XAF', max_length=3, verbose_name='devise'),
        ),
    ]
