# Generated by Django 5.2.17 on 2026-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_country_alter_tenant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='country',
            field=models.CharField(choices=[('CG', 'Congo-Brazzaville'), ('CD', 'République démocratique du Congo'), ('CN', 'Chine'), ('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('CI', 'Côte d’Ivoire'), ('TG', 'Togo'), ('SN', 'Sénégal'), ('NE', 'Niger')], default='CG', max_length=2, verbose_name='pays'),
        ),
    ]
