# Generated by Django 5.2.17 on 2026-09-11 01:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_plafond_quantite_ressource'),
        ('media', '0005_mediaasset_featured_alter_mediaasset_position'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='prix')),
                ('unit', models.CharField(choices=[('piece', "À l'unité"), ('pack', 'Paquet'), ('meter', 'Mètre'), ('gram', 'Gramme')], default='piece', max_length=10, verbose_name='vendu')),
                ('stock', models.IntegerField(blank=True, help_text="Laissez vide si vous n'en manquez jamais.", null=True, verbose_name='quantité en stock')),
                ('low_stock_at', models.PositiveSmallIntegerField(default=3, help_text="En dessous, l'article est signalé dans votre boutique.", verbose_name="seuil d'alerte")),
                ('active', models.BooleanField(default=True, verbose_name='proposé à la vente')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='photo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'boutique',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='« 3 paquets de mèches », « une perruque », « votre kit ».', max_length=150, verbose_name="ce qu'il faut")),
                ('detail', models.CharField(blank=True, help_text='Longueur, couleur, quantité conseillée…', max_length=255, verbose_name='précision')),
                ('mandatory', models.BooleanField(default=True, verbose_name='indispensable')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='catalog.service', verbose_name='prestation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'fourniture à prévoir',
                'verbose_name_plural': 'fournitures à prévoir',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequirementProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.product')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.requirement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'article proposé',
                'verbose_name_plural': 'articles proposés',
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='requirements', through='store.RequirementProduct', to='store.product', verbose_name='articles proposés'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_product_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='requirementproduct',
            constraint=models.UniqueConstraint(fields=('requirement', 'product'), name='unique_product_per_requirement'),
        ),
    ]
