# Generated by Django 5.2.17 on 2026-09-08 03:37

import apps.scheduling.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_extensions'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('blocked', 'Creneau bloque'), ('leave', 'Conge'), ('extra_opening', 'Ouverture exceptionnelle')], default='blocked', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='staff.staffmember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'indisponibilite',
                'verbose_name_plural': 'indisponibilites',
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['tenant', 'staff_member', 'starts_at', 'ends_at'], name='scheduling__tenant__6d3f2f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='availability_exception_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('requested', 'Demandee'), ('confirmed', 'Confirmee'), ('checked_in', 'Cliente arrivee'), ('completed', 'Terminee'), ('cancelled', 'Annulee'), ('no_show', 'Absente')], db_index=True, default='requested', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Mini-site'), ('staff', 'Saisie salon'), ('whatsapp', 'WhatsApp'), ('marketplace', 'Marketplace')], default='web', max_length=20)),
                ('service_name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('location_mode', models.CharField(choices=[('salon', 'Au salon'), ('home', 'A domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('customer_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.service')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='staff.staffmember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ('-starts_at',),
                'indexes': [models.Index(fields=['tenant', 'starts_at'], name='scheduling__tenant__7fa8a2_idx'), models.Index(fields=['tenant', 'staff_member', 'starts_at'], name='scheduling__tenant__dfb4a9_idx'), models.Index(fields=['tenant', 'status', 'starts_at'], name='scheduling__tenant__e40287_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending_payment', 'requested', 'confirmed', 'checked_in'])), expressions=[('tenant', '='), ('staff_member', '='), (apps.scheduling.models.TsTzRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='no_overlapping_bookings_per_staff')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('starts_at', models.TimeField(verbose_name='ouverture')),
                ('ends_at', models.TimeField(verbose_name='fermeture')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='staff.staffmember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'horaire',
                'verbose_name_plural': 'horaires',
                'ordering': ('weekday', 'starts_at'),
                'indexes': [models.Index(fields=['tenant', 'staff_member', 'weekday'], name='scheduling__tenant__f19fc3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='business_hours_end_after_start')],
            },
        ),
    ]
