# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityexception',
            options={'ordering': ('starts_at',), 'verbose_name': 'indisponibilité', 'verbose_name_plural': 'indisponibilités'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-starts_at',), 'verbose_name': 'réservation', 'verbose_name_plural': 'réservations'},
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='kind',
            field=models.CharField(choices=[('blocked', 'Créneau bloqué'), ('leave', 'Congé'), ('extra_opening', 'Ouverture exceptionnelle')], default='blocked', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_mode',
            field=models.CharField(choices=[('salon', 'Au salon'), ('home', 'À domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('requested', 'Demandée'), ('confirmed', 'Confirmée'), ('checked_in', 'Cliente arrivée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Absente')], db_index=True, default='requested', max_length=20),
        ),
    ]
