# Generated by Django 5.2.17 on 2026-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_availabilityexception_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('transfer', 'Virement'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
