# Generated by Django 5.2.17 on 2026-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_availabilityexception_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
