# Generated by Django 5.2.17 on 2026-09-10 04:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_booking_review_invited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='montant reçu'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False, verbose_name='acompte encaissé'),
        ),
    ]
