# Generated by Django 5.2.17 on 2026-09-10 11:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_booking_deposit_received_alter_booking_deposit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='frais de déplacement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_zone_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='zone de déplacement'),
        ),
    ]
