# Generated by Django 5.2.17 on 2026-09-10 19:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_deplacement_a_domicile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='options_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='supplément options'),
        ),
        migrations.AddField(
            model_name='booking',
            name='options_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='options retenues'),
        ),
    ]
