# Generated by Django 5.2.17 on 2026-09-10 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rls_ressources'),
        ('scheduling', '0009_options_retenues'),
        ('staff', '0004_alter_staffmember_tenant_alter_staffservice_tenant'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='nom')),
                ('phone', models.CharField(max_length=32, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_from', models.DateField(verbose_name='à partir du')),
                ('preferred_to', models.DateField(verbose_name="jusqu'au")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='précision')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('contacted', 'Contactée'), ('booked', 'Rendez-vous pris'), ('closed', 'Classée')], default='waiting', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='catalog.service', verbose_name='prestation souhaitée')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='staff.staffmember', verbose_name='prestataire souhaité')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': "inscription en liste d'attente",
                'verbose_name_plural': "liste d'attente",
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['tenant', 'status', 'preferred_from'], name='scheduling__tenant__9e9add_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('preferred_to__gte', models.F('preferred_from'))), name='waitlist_window_is_ordered')],
            },
        ),
    ]
