# Generated by Django 5.2.17 on 2026-09-11 01:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_rls_liste_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='items_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total boutique'),
        ),
        migrations.AddField(
            model_name='booking',
            name='items_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='articles achetés'),
        ),
    ]
