# Generated by Django 5.2.17 on 2026-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_devise_du_rendez_vous'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.CharField(default='fr', max_length=5, verbose_name='langue de la cliente'),
        ),
    ]
