# Generated by Django 5.2.17 on 2026-10-05 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0014_booking_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="compte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compte cliente",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, verbose_name="e-mail du rendez-vous"
            ),
        ),
    ]
