# Generated by Django 5.2.17 on 2026-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_remplir_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prix_initial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='promotion_montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='reduction_parrainage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
