# Generated by Django 5.2.17 on 2026-09-08 03:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'categorie de prestation',
                'verbose_name_plural': 'categories de prestation',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='duree en minutes')),
                ('price_kind', models.CharField(choices=[('fixed', 'Prix ferme'), ('from', 'A partir de'), ('quote', 'Sur devis')], default='fixed', max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('location_mode', models.CharField(choices=[('salon', 'Au salon'), ('home', 'A domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'prestation',
                'verbose_name_plural': 'prestations',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_category_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'active'], name='catalog_ser_tenant__de2466_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5)), name='service_duration_at_least_5_minutes'),
        ),
    ]
