# Generated by Django 5.2.17 on 2026-09-08 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('position', 'name'), 'verbose_name': 'catégorie de prestation', 'verbose_name_plural': 'catégories de prestation'},
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='durée en minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location_mode',
            field=models.CharField(choices=[('salon', 'Au salon'), ('home', 'À domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_kind',
            field=models.CharField(choices=[('fixed', 'Prix ferme'), ('from', 'À partir de'), ('quote', 'Sur devis')], default='fixed', max_length=10),
        ),
    ]
