# Generated by Django 5.2.17 on 2026-09-09 03:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_servicecategory_options_and_more'),
        ('media', '0003_alter_mediaasset_options_alter_mediaasset_kind_and_more'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='proposée à la réservation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='service',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='acompte demandé'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location_mode',
            field=models.CharField(choices=[('salon', 'Au salon'), ('home', 'À domicile'), ('hybrid', 'Les deux')], default='salon', max_length=10, verbose_name='lieu de la prestation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tarif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_kind',
            field=models.CharField(choices=[('fixed', 'Prix ferme'), ('from', 'À partir de'), ('quote', 'Sur devis')], default='fixed', max_length=10, verbose_name='type de tarif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon'),
        ),
    ]
