# Generated by Django 5.2.17 on 2026-09-10 19:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_service_active_alter_service_category_and_more'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='précision')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 pour une option sans supplément.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='supplément')),
                ('duration_delta_minutes', models.PositiveSmallIntegerField(default=0, help_text='Compté dans la recherche de créneau, pas seulement affiché.', verbose_name='temps supplémentaire (minutes)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='proposée à la réservation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.service', verbose_name='prestation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'option de prestation',
                'verbose_name_plural': 'options de prestation',
                'ordering': ('position', 'name'),
                'constraints': [models.UniqueConstraint(fields=('service', 'name'), name='unique_option_per_service')],
            },
        ),
    ]
