# Generated by Django 5.2.17 on 2026-09-10 20:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rls_serviceoption'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('kind', models.CharField(choices=[('chair', 'Fauteuil'), ('basin', 'Bac à shampooing'), ('room', 'Cabine'), ('equipment', 'Matériel')], default='chair', max_length=20, verbose_name='type')),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Combien vous en avez. Deux bacs : 2.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité disponible')),
                ('active', models.BooleanField(default=True, verbose_name='prise en compte')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='catalog.resource')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='catalog.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': "ressource d'une prestation",
                'verbose_name_plural': 'ressources des prestations',
            },
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_resource_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='serviceresource',
            constraint=models.UniqueConstraint(fields=('service', 'resource'), name='unique_service_resource'),
        ),
    ]
