# Generated by Django 5.2.17 on 2026-09-11 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rls_ressources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Combien vous en avez. Deux bacs : 2.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='quantité disponible'),
        ),
    ]
