# Generated by Django 5.2.17 on 2026-09-25 09:52

import apps.billing.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_tenant_alter_subscription_tenant'),
        ('media', '0010_reparer_medias_prives'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='moyen')),
                ('provider_name', models.CharField(blank=True, help_text='Obligatoire pour Mobile Money : MTN MoMo, Airtel Money, M-Pesa…', max_length=80, verbose_name='opérateur')),
                ('country', models.CharField(max_length=2, verbose_name='pays')),
                ('currency', models.CharField(choices=[('CNY', 'Yuan (CNY)'), ('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)')], max_length=3, verbose_name='devise')),
                ('account_number', models.CharField(blank=True, max_length=60, verbose_name='numéro de téléphone ou de compte')),
                ('account_holder', models.CharField(blank=True, max_length=120, verbose_name='titulaire du compte')),
                ('qr_image', models.ImageField(blank=True, max_length=255, upload_to=apps.billing.models.chemin_qr, verbose_name='QR code')),
                ('instructions', models.TextField(blank=True, max_length=1000, verbose_name='instructions')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'moyen de règlement de la plateforme',
                'verbose_name_plural': 'moyens de règlement de la plateforme',
                'ordering': ('position', 'kind', 'provider_name'),
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('manage_subscription_manually', 'Peut prolonger, suspendre ou réactiver un abonnement à la main')], 'verbose_name': 'abonnement', 'verbose_name_plural': 'abonnements'},
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='durée payée (mois)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='anchor_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_anchor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('transfer', 'Virement'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('trial', 'Essai'), ('solo', 'Solo'), ('salon', 'Salon'), ('pro', 'Pro'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', "Période d'essai"), ('active', 'Actif'), ('expired', 'Expiré'), ('pending_payment', 'Paiement en vérification'), ('suspended', 'Suspendu'), ('past_due', 'Impayé'), ('cancelled', 'Résilié')], default='trialing', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_months', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=2, verbose_name='pays')),
                ('currency', models.CharField(choices=[('CNY', 'Yuan (CNY)'), ('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)')], max_length=3, verbose_name='devise')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('method_kind', models.CharField(choices=[('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='moyen')),
                ('method_label', models.CharField(max_length=120, verbose_name='compte crédité')),
                ('method_account_number', models.CharField(blank=True, max_length=60)),
                ('method_account_holder', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(max_length=100, verbose_name='référence de transaction')),
                ('reference_normalisee', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente de vérification'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, verbose_name='note de vérification')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='motif du refus')),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='billing.platformpaymentmethod')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='preuve de paiement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='billing.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': "paiement d'abonnement",
                'verbose_name_plural': "paiements d'abonnement",
                'ordering': ('-created_at',),
                'permissions': [('review_subscriptionpaymentrequest', "Peut approuver ou refuser les paiements d'abonnement")],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('trial_started', 'Essai ouvert'), ('payment_submitted', 'Paiement déclaré'), ('payment_approved', 'Paiement approuvé'), ('payment_rejected', 'Paiement refusé'), ('manual_extension', 'Prolongation manuelle'), ('suspended', 'Suspendu'), ('reactivated', 'Réactivé'), ('expired', 'Expiré'), ('migrated', 'Reprise des abonnements existants')], max_length=30, verbose_name='événement')),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('period_end_before', models.DateTimeField(blank=True, null=True)),
                ('period_end_after', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.subscriptionpaymentrequest')),
            ],
            options={
                'verbose_name': "historique d'abonnement",
                'verbose_name_plural': 'historique des abonnements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('CNY', 'Yuan (CNY)'), ('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)')], max_length=3, verbose_name='devise')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('active', models.BooleanField(default=True, verbose_name='proposé')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='billing.plan')),
            ],
            options={
                'verbose_name': "tarif d'abonnement",
                'verbose_name_plural': "tarifs d'abonnement",
                'ordering': ('plan__position', 'currency'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'currency'), name='un_tarif_par_offre_et_devise'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='tarif_strictement_positif')],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionpaymentrequest',
            index=models.Index(fields=['tenant', '-created_at'], name='billing_sub_tenant__f218d5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpaymentrequest',
            index=models.Index(fields=['status', '-created_at'], name='billing_sub_status_5a5665_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpaymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant',), name='une_demande_en_attente_par_salon'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpaymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('method_kind', 'reference_normalisee'), name='reference_de_paiement_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpaymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='demande_montant_positif'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['tenant', '-created_at'], name='billing_sub_tenant__2d2ac1_idx'),
        ),
    ]
