# Generated by Django 5.2.17 on 2026-09-25 13:00

import uuid

import django.db.models.deletion
from django.db import migrations, models

from apps.common.rls import enable_rls


def corriger_description_essai(apps, schema_editor):
    """L'essai dure 14 jours : l'ancienne description en annoncait 30."""
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.using(schema_editor.connection.alias).filter(
        code="trial", description__contains="30 jours"
    ).update(description="Deux semaines pour essayer, sans engagement.")


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_offres_mensuelle_annuelle"),
        ("tenants", "0003_alter_tenant_country_alter_tenant_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("trial_7", "Fin d'essai dans 7 jours"),
                            ("trial_3", "Fin d'essai dans 3 jours"),
                            ("trial_1", "Fin d'essai demain"),
                            ("renewal_30", "Renouvellement dans 30 jours"),
                            ("renewal_7", "Renouvellement dans 7 jours"),
                            ("renewal_3", "Renouvellement dans 3 jours"),
                            ("renewal_1", "Renouvellement demain"),
                            ("grace", "Période terminée, délai de grâce"),
                            ("closed", "Accès fermé"),
                        ],
                        max_length=20,
                        verbose_name="rappel",
                    ),
                ),
                ("period_end", models.DateTimeField(verbose_name="fin de période visée")),
                (
                    "recipients",
                    models.PositiveSmallIntegerField(default=0, verbose_name="destinataires"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="billing.subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "rappel d'abonnement",
                "verbose_name_plural": "rappels d'abonnement",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "kind", "period_end"), name="un_rappel_par_periode"
                    )
                ],
            },
        ),
        *enable_rls("billing_subscriptionreminder"),
        migrations.RunPython(corriger_description_essai, migrations.RunPython.noop),
    ]
