# Generated by Django 5.2.17 on 2026-09-26 00:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_rappels_abonnement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("custom_domain", "Domaine personnalisé"),
                            ("customization", "Personnalisation avancée du site"),
                            ("whatsapp_assistant", "Assistant IA sur WhatsApp"),
                            ("platform_assistant", "Assistant IA dans l'espace pro"),
                            ("customer_assistant", "Assistant IA 24 h/24 pour les clientes"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "fonction Pro",
                "verbose_name_plural": "fonctions Pro",
                "ordering": ("position", "code"),
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="group",
            field=models.CharField(
                choices=[("standard", "Standard"), ("pro", "Pro")],
                default="standard",
                max_length=12,
                verbose_name="groupe",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="scheduled_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="subscription",
            name="scheduled_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="scheduled_period_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fin de la période programmée"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="scheduled_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="billing.plan",
                verbose_name="offre programmée",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="scheduled_price_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
        migrations.AlterField(
            model_name="plan",
            name="code",
            field=models.CharField(
                choices=[
                    ("trial", "Essai"),
                    ("solo", "Solo"),
                    ("salon", "Salon"),
                    ("pro", "Pro"),
                    ("monthly", "Mensuel"),
                    ("yearly", "Annuel"),
                    ("pro_monthly", "Pro mensuel"),
                    ("pro_yearly", "Pro annuel"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("trial_started", "Essai ouvert"),
                    ("payment_submitted", "Paiement déclaré"),
                    ("payment_approved", "Paiement approuvé"),
                    ("payment_rejected", "Paiement refusé"),
                    ("manual_extension", "Prolongation manuelle"),
                    ("suspended", "Suspendu"),
                    ("reactivated", "Réactivé"),
                    ("expired", "Expiré"),
                    ("migrated", "Reprise des abonnements existants"),
                    ("upgraded", "Passage à Pro"),
                    ("downgrade_scheduled", "Retour à Standard programmé"),
                    ("plan_changed", "Changement d'offre appliqué"),
                ],
                max_length=30,
                verbose_name="événement",
            ),
        ),
    ]
