# Generated by Django 5.2.17 on 2026-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_retrait_offres_solo_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='montant_catalogue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='tarif du catalogue'),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='remise_montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='remise de parrainage'),
        ),
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='remise_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise de parrainage (%)'),
        ),
    ]
