# Generated by Django 5.2.17 on 2026-10-08 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_subscriptionpaymentrequest_montant_catalogue_and_more'),
        ('tenants', '0005_alter_tenant_country_alter_tenant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpaymentrequest',
            name='etat_encaissement',
            field=models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('rembourse', 'Remboursé'), ('conteste', 'Contesté')], default='confirme', max_length=12),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='currency',
            field=models.CharField(choices=[('CNY', 'Yuan (CNY)'), ('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)'), ('XOF', 'Franc CFA BCEAO (XOF)')], max_length=3, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='platformpaymentmethod',
            name='currency',
            field=models.CharField(choices=[('CNY', 'Yuan (CNY)'), ('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)'), ('XOF', 'Franc CFA BCEAO (XOF)')], max_length=3, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='platformpaymentmethod',
            name='kind',
            field=models.CharField(choices=[('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('mobile_money', 'Mobile Money'), ('kkiapay', 'KKIAPAY')], max_length=20, verbose_name='moyen'),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentrequest',
            name='currency',
            field=models.CharField(choices=[('CNY', 'Yuan (CNY)'), ('USD', 'Dollar américain (USD)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)'), ('XOF', 'Franc CFA BCEAO (XOF)')], max_length=3, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentrequest',
            name='method_kind',
            field=models.CharField(choices=[('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('mobile_money', 'Mobile Money'), ('kkiapay', 'KKIAPAY')], max_length=20, verbose_name='moyen'),
        ),
        migrations.CreateModel(
            name='KkiapayIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sandbox', models.BooleanField()),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='en_attente', max_length=12)),
                ('expire_le', models.DateTimeField()),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionpaymentrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('sandbox', 'transaction_id'), name='kkiapay_transaction_unique')],
            },
        ),
    ]
