# Generated by Django 5.2.17 on 2026-10-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_subscriptionpaymentrequest_etat_encaissement_and_more'),
        ('tenants', '0005_alter_tenant_country_alter_tenant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkiapayintent',
            name='demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionpaymentrequest'),
        ),
        migrations.AlterField(
            model_name='kkiapayintent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
    ]
