# Generated by Django 5.2.17 on 2026-10-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_kkiapayintent_demande_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kkiapayintent',
            options={'verbose_name': 'intention de paiement KKIAPAY', 'verbose_name_plural': 'paiements KKIAPAY'},
        ),
    ]
