# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='kind',
            field=models.CharField(choices=[('platform_subdomain', 'Sous-domaine plateforme'), ('custom_domain', 'Domaine personnalisé')], default='platform_subdomain', max_length=32),
        ),
    ]
