# Generated by Django 5.2.17 on 2026-09-26 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.common.rls import enable_rls


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0002_alter_domain_kind"),
        ("tenants", "0003_alter_tenant_country_alter_tenant_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hostname", models.CharField(max_length=253, verbose_name="domaine")),
                ("token", models.CharField(max_length=64, verbose_name="jeton de vérification")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente de vérification"), ("connected", "Relié")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de domaine",
                "verbose_name_plural": "demandes de domaine",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "hostname"), name="une_demande_par_domaine_et_salon"
                    )
                ],
            },
        ),
        *enable_rls("domains_domainclaim"),
    ]
