# Generated by Django 5.2.17 on 2026-09-19 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('reservation', 'Nouvelle demande'), ('acompte_a_verifier', 'Acompte à vérifier'), ('acompte_expire', 'Acompte non réglé'), ('annulation', 'Rendez-vous annulé'), ('avis', 'Nouvel avis'), ('liste_attente', "Liste d'attente"), ('salon_inscrit', 'Nouveau salon'), ('facture', 'Facturation'), ('incident', 'Incident')], db_index=True, max_length=32, verbose_name='genre')),
                ('titre', models.CharField(max_length=120, verbose_name='titre')),
                ('corps', models.CharField(blank=True, max_length=300, verbose_name='détail')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='lien')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'notification de salon',
                'verbose_name_plural': 'notifications de salon',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'recipient', '-created_at'], name='notif_salon_boite_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(choices=[('reservation', 'Nouvelle demande'), ('acompte_a_verifier', 'Acompte à vérifier'), ('acompte_expire', 'Acompte non réglé'), ('annulation', 'Rendez-vous annulé'), ('avis', 'Nouvel avis'), ('liste_attente', "Liste d'attente"), ('salon_inscrit', 'Nouveau salon'), ('facture', 'Facturation'), ('incident', 'Incident')], db_index=True, max_length=32, verbose_name='genre')),
                ('titre', models.CharField(max_length=120, verbose_name='titre')),
                ('corps', models.CharField(blank=True, max_length=300, verbose_name='détail')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='lien')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_notifications', to='tenants.tenant', verbose_name='salon concerné')),
            ],
            options={
                'verbose_name': 'notification plateforme',
                'verbose_name_plural': 'notifications plateforme',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notif_plateforme_boite_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portee', models.CharField(choices=[('salon', 'Tableau de bord'), ('plateforme', 'Administration')], db_index=True, default='salon', max_length=12, verbose_name='portée')),
                ('endpoint', models.TextField(unique=True, verbose_name='adresse de remise')),
                ('cle_p256dh', models.CharField(max_length=200, verbose_name='clé p256dh')),
                ('cle_auth', models.CharField(max_length=100, verbose_name='clé auth')),
                ('appareil', models.CharField(blank=True, max_length=80, verbose_name='appareil')),
                ('derniere_reussite', models.DateTimeField(blank=True, null=True, verbose_name='dernier envoi réussi')),
                ('echecs', models.PositiveSmallIntegerField(default=0, verbose_name='échecs consécutifs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='compte')),
            ],
            options={
                'verbose_name': 'appareil abonné',
                'verbose_name_plural': 'appareils abonnés',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'portee'], name='push_par_compte_idx')],
            },
        ),
    ]
