# Generated by Django 5.2.17 on 2026-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='genre',
            field=models.CharField(choices=[('reservation', 'Nouvelle demande'), ('acompte_a_verifier', 'Acompte à vérifier'), ('acompte_expire', 'Acompte non réglé'), ('annulation', 'Rendez-vous annulé'), ('avis', 'Nouvel avis'), ('liste_attente', "Liste d'attente"), ('abonnement', 'Abonnement'), ('salon_inscrit', 'Nouveau salon'), ('paiement_abonnement', "Paiement d'abonnement à vérifier"), ('facture', 'Facturation'), ('incident', 'Incident')], db_index=True, max_length=32, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='platformnotification',
            name='genre',
            field=models.CharField(choices=[('reservation', 'Nouvelle demande'), ('acompte_a_verifier', 'Acompte à vérifier'), ('acompte_expire', 'Acompte non réglé'), ('annulation', 'Rendez-vous annulé'), ('avis', 'Nouvel avis'), ('liste_attente', "Liste d'attente"), ('abonnement', 'Abonnement'), ('salon_inscrit', 'Nouveau salon'), ('paiement_abonnement', "Paiement d'abonnement à vérifier"), ('facture', 'Facturation'), ('incident', 'Incident')], db_index=True, max_length=32, verbose_name='genre'),
        ),
    ]
