# Generated by Django 5.2.17 on 2026-10-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="portee",
            field=models.CharField(
                choices=[
                    ("salon", "Tableau de bord"),
                    ("plateforme", "Administration"),
                    ("cliente", "Espace cliente"),
                ],
                db_index=True,
                default="salon",
                max_length=12,
                verbose_name="portée",
            ),
        ),
    ]
