# Generated by Django 5.2.17 on 2026-09-09 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_customer_tenant'),
        ('scheduling', '0005_alter_availabilityexception_tenant_and_more'),
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=150, verbose_name='signature')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('status', models.CharField(choices=[('published', 'Publié'), ('hidden', 'Masqué')], default='published', max_length=12, verbose_name='statut')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='scheduling.booking', verbose_name='rendez-vous')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customers.customer', verbose_name='cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='reviews_rev_tenant__34f9d1_idx')],
            },
        ),
    ]
