# Generated by Django 5.2.17 on 2026-09-15 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_cleanliness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='la propreté du salon'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_punctuality',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='la ponctualité'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_result',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='le résultat'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='le rapport qualité-prix'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_welcome',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="l'accueil"),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Moyenne des critères notés, arrondie.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="note d'ensemble"),
        ),
    ]
