# Generated by Django 5.2.17 on 2026-09-22 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_country_alter_tenant_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=64, verbose_name='modele')),
                ('object_id', models.UUIDField(verbose_name='objet')),
                ('field', models.CharField(max_length=64, verbose_name='champ')),
                ('language', models.CharField(max_length=5, verbose_name='langue')),
                ('text', models.TextField(verbose_name='texte traduit')),
                ('source_digest', models.CharField(max_length=64, verbose_name='empreinte du texte source')),
                ('origin', models.CharField(choices=[('machine', 'traduction automatique'), ('salon', 'corrigee par le salon')], default='machine', max_length=16, verbose_name='origine')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'traduction',
                'verbose_name_plural': 'traductions',
                'indexes': [models.Index(fields=['tenant', 'language'], name='traduction_salon_langue')],
                'constraints': [models.UniqueConstraint(fields=('model', 'object_id', 'field', 'language'), name='traduction_unique_par_champ_et_langue')],
            },
        ),
    ]
