# Generated by Django 5.2.17 on 2026-09-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffservice',
            options={'verbose_name': 'compétence', 'verbose_name_plural': 'compétences'},
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='specialty',
            field=models.CharField(blank=True, max_length=150, verbose_name='spécialité'),
        ),
    ]
