# Generated by Django 5.2.17 on 2026-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staffmember_tenant_alter_staffservice_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retiré le'),
        ),
    ]
